
/****** Object:  Table [dbo].[CodigoSituacaoTributaria]    Script Date: 12/16/2025 15:44:38 ******/
SET IDENTITY_INSERT [dbo].[CodigoSituacaoTributaria] ON
INSERT [dbo].[CodigoSituacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (1, N'000', N'Tributação integral')
INSERT [dbo].[CodigoSituacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (2, N'010', N'Tributação com alíquotas uniformes')
INSERT [dbo].[CodigoSituacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (3, N'011', N'Tributação com alíquotas uniformes reduzidas')
INSERT [dbo].[CodigoSituacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (4, N'200', N'Alíquota reduzida')
INSERT [dbo].[CodigoSituacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (5, N'220', N'Alíquota fixa')
INSERT [dbo].[CodigoSituacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (6, N'221', N'Alíquota fixa proporcional')
INSERT [dbo].[CodigoSituacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (7, N'222', N'Redução de Base de Cálculo')
INSERT [dbo].[CodigoSituacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (8, N'400', N'Isenção')
INSERT [dbo].[CodigoSituacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (9, N'410', N'Imunidade e não incidência')
INSERT [dbo].[CodigoSituacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (10, N'510', N'Diferimento')
INSERT [dbo].[CodigoSituacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (11, N'515', N'Diferimento com redução de alíquota')
INSERT [dbo].[CodigoSituacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (12, N'550', N'Suspensão')
INSERT [dbo].[CodigoSituacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (13, N'620', N'Tributação Monofásica')
INSERT [dbo].[CodigoSituacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (14, N'800', N'Transferência de crédito')
INSERT [dbo].[CodigoSituacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (15, N'810', N'Ajuste de IBS na ZFM')
INSERT [dbo].[CodigoSituacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (16, N'811', N'Ajustes')
INSERT [dbo].[CodigoSituacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (17, N'820', N'Tributação em declaração de regime específico')
INSERT [dbo].[CodigoSituacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (18, N'830', N'Exclusão da Base de Cálculo')
SET IDENTITY_INSERT [dbo].[CodigoSituacaoTributaria] OFF
/****** Object:  Table [dbo].[CodigoClassificacaoTributaria]    Script Date: 12/16/2025 15:44:38 ******/
SET IDENTITY_INSERT [dbo].[CodigoClassificacaoTributaria] ON
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (1, N'000001', N'Situações tributadas integralmente pelo IBS e CBS.')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (2, N'000002', N'Exploração de via')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (3, N'010001', N'Operações do FGTS não realizadas pela Caixa Econômica Federal')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (4, N'010002', N'Operações do serviço financeiro')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (5, N'011001', N'Planos de assistência funerária.')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (6, N'011002', N'Planos de assistência à saúde')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (7, N'011003', N'Intermediação de planos de assistência à saúde')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (8, N'011004', N'Concursos e prognósticos')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (9, N'011005', N'Planos de assistência à saúde de animais domésticos')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (10, N'200001', N'Aquisições realizadas entre empresas autorizadas a operar em zonas de processamento de exportação')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (11, N'200002', N'Fornecimento ou importação para produtor rural não contribuinte ou TAC')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (12, N'200003', N'Vendas de produtos destinados à alimentação humana (Anexo I)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (13, N'200004', N'Venda de dispositivos médicos (Anexo XII)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (14, N'200005', N'Venda de dispositivos médicos adquiridos por órgãos da administração pública (Anexo IV)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (15, N'200006', N'Situação de emergência de saúde pública reconhecida pelo Poder público (Anexo XII)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (16, N'200007', N'Fornecimento dos dispositivos de acessibilidade próprios para pessoas com deficiência (Anexo XIII)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (17, N'200008', N'Fornecimento dos dispositivos de acessibilidade próprios para pessoas com deficiência adquiridos por órgãos da administração pública (Anexo V)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (18, N'200009', N'Fornecimento de medicamentos (Anexo XIV)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (19, N'200010', N'Fornecimento dos medicamentos registrados na Anvisa, adquiridos por órgãos da administração pública')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (20, N'200011', N'Fornecimento das composições para nutrição enteral e parenteral quando adquiridas por órgãos da administração pública (Anexo VI)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (21, N'200012', N'Situação de emergência de saúde pública reconhecida pelo Poder público (Anexo XIV)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (22, N'200013', N'Fornecimento de tampões higiênicos, absorventes higiênicos internos ou externos')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (23, N'200014', N'Fornecimento dos produtos hortícolas, frutas e ovos (Anexo XV)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (24, N'200015', N'Venda de automóveis de passageiros de fabricação nacional adquiridos por motoristas profissionais ou pessoas com deficiência')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (25, N'200016', N'Prestação de serviços de pesquisa e desenvolvimento por Instituição Científica, Tecnológica e de Inovação (ICT)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (26, N'200017', N'Operações relacionadas ao FGTS')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (27, N'200018', N'Operações de resseguro e retrocessão')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (28, N'200019', N'Importador dos serviços financeiros contribuinte')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (29, N'200020', N'Operação praticada por sociedades cooperativas optantes por regime específico do IBS e CBS')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (30, N'200021', N'Serviços de transporte público coletivo de passageiros ferroviário e hidroviário')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (31, N'200022', N'Operação originada fora da ZFM que destine bem material industrializado a contribuinte estabelecido na ZFM')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (32, N'200023', N'Operação realizada por indústria incentivada que destine bem material intermediário para outra indústria incentivada na ZFM')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (33, N'200024', N'Operação originada fora das Áreas de Livre Comércio destinadas a contribuinte estabelecido nas Áreas de Livre Comércio')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (34, N'200025', N'Fornecimento dos serviços de educação relacionados ao Programa Universidade para Todos (Prouni)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (35, N'200026', N'Locação de imóveis localizados nas zonas reabilitadas')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (36, N'200027', N'Operações de locação, cessão onerosa e arrendamento de bens imóveis')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (37, N'200028', N'Fornecimento dos serviços de educação (Anexo II)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (38, N'200029', N'Fornecimento dos serviços de saúde humana (Anexo III)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (39, N'200030', N'Venda dos dispositivos médicos (Anexo IV)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (40, N'200031', N'Fornecimento dos dispositivos de acessibilidade próprios para pessoas com deficiência (Anexo V)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (41, N'200032', N'Fornecimento dos medicamentos registrados na Anvisa ou produzidos por farmácias de manipulação, ressalvados os medicamentos sujeitos à alíquota zero')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (42, N'200033', N'Fornecimento das composições para nutrição enteral e parenteral (Anexo VI)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (43, N'200034', N'Fornecimento dos alimentos destinados ao consumo humano (Anexo VII)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (44, N'200035', N'Fornecimento dos produtos de higiene pessoal e limpeza (Anexo VIII)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (45, N'200036', N'Fornecimento de produtos agropecuários, aquícolas, pesqueiros, florestais e extrativistas vegetais in natura')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (46, N'200037', N'Fornecimento de serviços ambientais de conservação ou recuperação da vegetação nativa')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (47, N'200038', N'Fornecimento dos insumos agropecuários e aquícolas (Anexo IX)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (48, N'200039', N'Fornecimento dos serviços e o licenciamento ou cessão dos direitos destinados às produções nacionais artísticas (Anexo X)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (49, N'200040', N'Fornecimento de serviços de comunicação institucional à administração pública')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (50, N'200043', N'Fornecimento à administração pública dos serviços e dos bens relativos à soberania (Anexo XI)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (51, N'200044', N'Operações e prestações de serviços de segurança da informação e segurança cibernética desenv por sociedade que tenha sócio brasileiro (Anexo XI)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (52, N'200045', N'Operações relacionadas a projetos de reabilitação urbana de zonas históricas e de áreas críticas de recuperação e reconversão urbanística')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (53, N'200046', N'Operações com bens imóveis')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (54, N'200047', N'Bares e Restaurantes')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (55, N'200048', N'Hotelaria, Parques de Diversão e Parques Temáticos')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (56, N'200049', N'Transporte coletivo de passageiros rodoviário, ferroviário e hidroviário')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (57, N'200050', N'Serviços de transporte aéreo regional coletivo de passageiros ou de carga')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (58, N'200051', N'Agências de Turismo')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (59, N'200052', N'Prestação de serviços de profissões intelectuais')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (60, N'220001', N'Incorporação imobiliária submetida ao regime especial de tributação')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (61, N'220002', N'Incorporação imobiliária submetida ao regime especial de tributação')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (62, N'220003', N'Alienação de imóvel decorrente de parcelamento do solo')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (63, N'221001', N'Locação, cessão onerosa ou arrendamento de bem imóvel com alíquota sobre a receita bruta')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (64, N'222001', N'Transporte internacional de passageiros, caso os trechos de ida e volta sejam vendidos em conjunto')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (65, N'400001', N'Fornecimento de serviços de transporte público coletivo de passageiros rodoviário e metroviário')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (66, N'410001', N'Fornecimento de bonificações quando constem no documento fiscal e que não dependam de evento posterior')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (67, N'410002', N'Transferências entre estabelecimentos pertencentes ao mesmo contribuinte')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (68, N'410003', N'Doações sem contraprestação em benefício do doador')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (69, N'410004', N'Exportações de bens e serviços')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (70, N'410005', N'Fornecimentos realizados pela União, pelos Estados, pelo Distrito Federal e pelos Municípios')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (71, N'410006', N'Fornecimentos realizados por entidades religiosas e templos de qualquer culto')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (72, N'410007', N'Fornecimentos realizados por partidos políticos')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (73, N'410008', N'Fornecimentos de livros, jornais, periódicos e do papel destinado a sua impressão')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (74, N'410009', N'Fornecimentos de fonogramas e videofonogramas musicais produzidos no Brasil')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (75, N'410010', N'Fornecimentos de serviço de comunicação nas modalidades de radiodifusão sonora e de sons e imagens de recepção livre e gratuita')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (76, N'410011', N'Fornecimentos de ouro, quando definido em lei como ativo financeiro ou instrumento cambial')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (77, N'410012', N'Fornecimento de condomínio edilício não optante pelo regime regular')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (78, N'410013', N'Exportações de combustíveis')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (79, N'410014', N'Fornecimento de produtor rural não contribuinte')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (80, N'410015', N'Fornecimento por transportador autônomo não contribuinte')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (81, N'410016', N'Fornecimento ou aquisição de resíduos sólidos')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (82, N'410017', N'Aquisição de bem móvel com crédito presumido sob condição de revenda realizada')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (83, N'410018', N'Operações relacionadas aos fundos garantidores e executores de políticas públicas')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (84, N'410019', N'Exclusão da gorjeta na base de cálculo no fornecimento de alimentação')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (85, N'410020', N'Exclusão do valor de intermediação na base de cálculo no fornecimento de alimentação')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (86, N'410021', N'Contribuição de que trata o art.')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (87, N'149', N'A da Constituição Federal')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (88, N'410022', N'Consolidação da propriedade do bem pelo credor')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (89, N'410023', N'Alienação de bens móveis ou imóveis que tenham sido objeto de garantia em que o prestador da garantia não seja contribuinte')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (90, N'410024', N'Consolidação da propriedade do bem pelo grupo de consórcio')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (91, N'410025', N'Alienação de bem que tenha sido objeto de garantia em que o prestador da garantia não seja contribuinte')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (92, N'410026', N'Doação com anulação de crédito')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (93, N'410999', N'Operações não onerosas sem previsão de tributação, não especificadas anteriormente')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (94, N'510001', N'Operações, sujeitas a diferimento, com energia elétrica, relativas à geração, comercialização, distribuição e transmissão')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (95, N'515001', N'Operações, sujeitas a diferimento, com insumos agropecuários e aquícolas destinados a produtor rural não contribuinte (Anexo IX)')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (96, N'550001', N'Exportações de bens materiais')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (97, N'550002', N'Regime de Trânsito')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (98, N'550006', N'Regimes de Permanência Temporária')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (99, N'550007', N'Regimes de Aperfeiçoamento')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (100, N'550008', N'Importação de bens para o Regime de Repetro-Temporário')
GO
print 'Processed 100 total records'
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (101, N'550009', N'GNL-Temporário')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (102, N'550010', N'Repetro-Permanente')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (103, N'550011', N'Repetro-Industrialização')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (104, N'550012', N'Repetro-Nacional')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (105, N'550013', N'Repetro-Entreposto')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (106, N'550014', N'Zona de Processamento de Exportação')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (107, N'550015', N'Regime Tributário para Incentivo à Modernização e à Ampliação da Estrutura Portuária')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (108, N'550016', N'Regime Especial de Incentivos para o Desenvolvimento da Infraestrutura')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (109, N'550017', N'Regime Tributário para Incentivo à Atividade Econômica Naval')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (110, N'550018', N'Desoneração da aquisição de bens de capital')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (111, N'550019', N'Importação de bem material por indústria incentivada para utilização na ZFM')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (112, N'550020', N'Áreas de livre comércio')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (113, N'550021', N'Industrialização destinada a exportações')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (114, N'620001', N'Tributação monofásica sobre combustíveis')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (115, N'620002', N'Tributação monofásica com responsabilidade pela retenção sobre combustíveis')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (116, N'620003', N'Tributação monofásica com tributos retidos por responsabilidade sobre combustíveis')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (117, N'620004', N'Tributação monofásica sobre mistura de EAC com gasolina A em percentual superior ao obrigatório')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (118, N'620005', N'Tributação monofásica sobre mistura de EAC com gasolina A em percentual inferior ao obrigatório')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (119, N'620006', N'Tributação monofásica sobre combustíveis cobrada anteriormente')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (120, N'800001', N'Fusão, cisão ou incorporação')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (121, N'800002', N'Transferência de crédito do associado, inclusive as cooperativas singulares')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (122, N'810001', N'Crédito presumido sobre o valor apurado nos fornecimentos a partir da ZFM')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (123, N'811001', N'Anulação de Crédito por Saídas Imunes/Isentas')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (124, N'811002', N'Débitos de notas fiscais não processadas na apuração')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (125, N'811003', N'Desenquadramento do Simples Nacional')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (126, N'820001', N'Documento com informações de fornecimento de serviços de planos de assinstência à saúde')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (127, N'820002', N'Documento com informações de fornecimento de serviços de planos de assinstência funerária')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (128, N'820003', N'Documento com informações de fornecimento de serviços de planos de assinstência à saúde de animais domésticos')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (129, N'820004', N'Documento com informações de prestação de serviços de consursos de prognósticos')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (130, N'820005', N'Documento com informações de alienação de bens imóveis')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (131, N'820006', N'Documento com informações de fornecimento de serviços de exploração de via')
INSERT [dbo].[CodigoClassificacaoTributaria] ([Id], [Codigo], [Nome]) VALUES (132, N'830001', N'Documento com exclusão da BC da CBS e do IBS de energia elétrica fornecida pela distribuidora à UC')
SET IDENTITY_INSERT [dbo].[CodigoClassificacaoTributaria] OFF
